# .lychee.toml

# Base URL of your published site
base = "https://san-serif-sentiments.github.io/ai-glossary"

# Retries & concurrency
cache = true
max-concurrency = 6
retry-wait-time = 2
retry-count = 2

# Force GET (some servers 403/405 on HEAD); add a browser UA
method = "GET"
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

# Accept common success/redirect/ratelimit statuses
accept = [200, 201, 202, 204, 206, 301, 302, 307, 308, 429]

# Sites that block automated requests even with GET+UA
exclude = [
  "https://platform.openai.com/docs/*" # OpenAI Docs often 403 to bots
]

# Ignore CI/config folders
exclude_path = [
  "^\\.github/.*"
]
