# Base URL (GitHub Pages origin)
base = "https://san-serif-sentiments.github.io/ai-glossary"

# Retries & concurrency
cache = true
max-concurrency = 4     # safer for GitHub
retry-wait-time = 2
retry-count = 3

# Use GET with browser UA to avoid 403 on HEAD
method = "GET"
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

# Accept common success/redirect/ratelimit statuses
accept = [200, 201, 202, 204, 206, 301, 302, 307, 308, 429]

############################
# Rewrite root-relative links (e.g. /terms/foo → live Pages URL)
[[rewrite]]
from = "^/(terms|categories|roles|resources|prompting|governance-dashboard|search|contributing|data-model|keyword-backlog|term-request)(/.*)?$"
to   = "https://san-serif-sentiments.github.io/ai-glossary/$1$2"

############################
# Exclude external domains that block bots or rate-limit heavily
exclude = [
  "https://github.com/san-serif-sentiments/ai-glossary/edit/.*",
  "https://platform.openai.com/docs/.*",
  "https://help.openai.com/.*",
  "https://post.parliament.uk/.*",
  "https://huggingface.co/docs/.*",
  "https://huggingface.co/docs/tokenizers/.*",
  "https://www.weforum.org/.*",
  "https://www.oecd.org/.*",
  "https://www.ftc.gov/.*",
  "https://www.accessnow.org/.*",
  "https://www.partnershiponai.org/.*",
  "https://www.datadoghq.com/.*"
]

############################
# Ignore local static assets
exclude_path = [
  "^\\.github/.*",
  ".*/assets/.*",
  ".*/.*\\.(css|js|png|jpg|jpeg|svg|ico|gif)$"
]
