name: Build Release Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate glossary entries
        run: make validate

      - name: Generate JSON outputs
        run: python scripts/build_index.py --data-dir data/terms --output-dir build

      - name: Build MkDocs site
        run: |
          cd site
          mkdocs build --strict

      - name: Upload glossary artifact
        uses: actions/upload-artifact@v4
        with:
          name: glossary-json
          path: build/glossary.json

      - name: Upload search index
        uses: actions/upload-artifact@v4
        with:
          name: search-index
          path: build/search-index.json

      - name: Upload static site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/site
