name: Validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt codespell mkdocs mkdocs-material

      - name: Spell-check content
        run: codespell --skip=".git,build,site/site,.venv" --ignore-words=.codespellignore

      - name: Validate glossary entries
        run: make validate

      - name: Build glossary assets
        run: make build

      - name: Run unit tests
        run: python -m unittest discover -s tests

      # 👇 Build site BEFORE link check
      - name: Build documentation site
        run: |
          mkdocs build -f site/mkdocs.yml -d site_build

      # 👇 Check links in built HTML instead of raw Markdown
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lychee.toml --no-progress site_build
