name: Validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt codespell mkdocs mkdocs-material

      - name: Spell-check content
        run: codespell --skip=".git,build,site/site,.venv" --ignore-words=.codespellignore

      - name: Validate glossary entries
        run: make validate

      - name: Build glossary assets
        run: make build

      - name: Run unit tests
        run: python -m unittest discover -s tests

      # Build the docs to a known folder at the repo root
      - name: Build documentation site
        run: mkdocs build -f site/mkdocs.yml -d site_build

      # Prove the folder exists (helps debug paths)
      - name: Verify build output
        run: |
          ls -la
          ls -la site_build || (echo "site_build not found" && exit 1)

      # Run lychee *inside* site_build so "." is unambiguous
      - name: Check links (Lychee on built HTML)
        uses: lycheeverse/lychee-action@v2
        working-directory: ${{ github.workspace }}/site_build
        with:
          args: --config ../.lychee.toml --no-progress .
