name: Validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate glossary entries
        run: make validate

      - name: Build JSON outputs
        run: python scripts/build_index.py --data-dir data/terms --output-dir build

      - name: Build documentation site
        run: |
          cd site
          mkdocs build --strict
